# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-05 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0004_auto_20180705_0122'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poicommentreply',
            name='poi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pois.Poi', verbose_name='评论所属文章'),
        ),
        migrations.AlterField(
            model_name='poicomment',
            name='comment_id',
            field=models.CharField(db_index=True, default='ed9257567ff111e8be3f309c23a2312b', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poicommentreply',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.PoiCommentReply', verbose_name='回复对象'),
        ),
    ]
