# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-05 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180705_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poicomment',
            name='comment_id',
            field=models.CharField(db_index=True, default='a90928207ff211e8be3f309c23a2312b', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poicommentreply',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.PoiComment', verbose_name='一级评论'),
        ),
    ]
