# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-04 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.CharField(db_index=True, default='69918f997f5011e8be3f309c23a2312b', max_length=32, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='标签创建时间')),
            ],
        ),
    ]
