# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-04 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(db_index=True, default='562a6d237f5911e8be3f309c23a2312b', max_length=32, primary_key=True, serialize=False),
        ),
    ]
