# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-05 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20180704_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(db_index=True, default='c75dce5b7ff211e8be3f309c23a2312b', max_length=32, primary_key=True, serialize=False),
        ),
    ]
