# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-05 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0002_auto_20180704_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='poi_id',
            field=models.CharField(db_index=True, default='4e1d31087ff111e8be3f309c23a2312b', max_length=32, primary_key=True, serialize=False),
        ),
    ]
